version: '2'
services:
    distribuidas-db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: distribuidas-db
        environment:
            - SA_PASSWORD=Fresquit0
            - ACCEPT_EULA=Y
        ports:
            - 5432:3306
        cap_add:
            - SYS_NICE