version: '2'
services:
    distribuidas-db:
        image: mysql
        container_name: distribuidas-db
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword1
            - MYSQL_DATABASE=auctions
            - MYSQL_USER=user1
            - MYSQL_PASSWORD=password1
        ports:
            - 5432:3306
        cap_add:
            - SYS_NICE